Fix luna-service2 usage
:Release Notes:
Since luna-service2 submission 143 from September 2012 ls2 headers
should be included from luna-service2 directory.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/548214

TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/git/include -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0=/usr/src/debug/com.webos.service.audiofocusmanager/1.0.0-6-r0                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0=/usr/src/debug/com.webos.service.audiofocusmanager/1.0.0-6-r0                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -DNDEBUG   -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/recipe-sysroot/usr/lib/glib-2.0/include -MD -MT CMakeFiles/audiofocusmanager.dir/src/utils.cpp.o -MF CMakeFiles/audiofocusmanager.dir/src/utils.cpp.o.d -o CMakeFiles/audiofocusmanager.dir/src/utils.cpp.o -c TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/git/src/utils.cpp
In file included from TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/git/src/utils.cpp:19:
TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.audiofocusmanager/1.0.0-6-r0/git/include/common.h:22:10: fatal error: lunaservice.h: No such file or directory
   22 | #include <lunaservice.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-10642] Remove the temporary work around from 2012 from luna-service2 recipe
[WRP-11230] com.webos.service.audiofocusmanager: Fix luna-service2 usage
[WRP-10791] CCC: Various build fixes

Change-Id: I2ee78e0b2b86172a3910befa4de8d2b40ed72f30
Reviewed-on: http://gpro.lge.com/c/webosose/com.webos.service.audiofocusmanager/+/348165
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Sushovan Gangopadhy <sushovan.g@lge.com>
Tested-by: Martin Jansa <martin2.jansa@lgepartner.com>